# Generated by Django 5.1.6 on 2025-03-28 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('yurudik_shaxs', 'Yuridik Shaxs'), ('yakka_tartibdagi_tadbirkor', 'Yakka tartibdagi tadbirkor'), ('ozini_ozi_band_qilgan', "O'zini o'zi band qilgan")], max_length=30)),
                ('name_of_legal_entity', models.CharField(max_length=255)),
                ('sitr', models.CharField(max_length=255)),
                ('ifut_code', models.CharField(max_length=255)),
                ('seller_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.selleraccount')),
            ],
        ),
    ]
