# Generated by Django 5.1.6 on 2025-03-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('registration_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.registrationform')),
            ],
        ),
    ]
