# Generated by Django 5.1.6 on 2025-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=13, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('otp', models.CharField(max_length=4, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
